

# This file was *autogenerated* from the file ./3-pointwise.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_6 = Integer(6); _sage_const_4 = Integer(4)#!/usr/local/bin/sage

def label_pairs(n):
    N = []
    L = tuples((ellipsis_range(_sage_const_1 ,Ellipsis,n)),_sage_const_3 )
    for x in L:
        #print x[0] == x[1] or x[0] == x[2] or x[1] == x[2]
        if x[_sage_const_0 ] == x[_sage_const_1 ] or x[_sage_const_0 ] == x[_sage_const_2 ] or x[_sage_const_1 ] == x[_sage_const_2 ]:
            pass
        else:
            N.append(x)
    D = dict()
    i = _sage_const_1 
    for x in N:
        D[x] = i
        i += _sage_const_1 
    return D,N

def action_of_element_as_permutation(f,T):
    return (f(T[_sage_const_0 ]),f(T[_sage_const_1 ]),f(T[_sage_const_2 ]))

def SymmetricGroup_acting_on_triples(n):
    PermGens = []
    G = SymmetricGroup(n)
    S = G.minimal_generating_set()
    K = label_pairs(n)
    L = K[_sage_const_1 ]
    D = K[_sage_const_0 ]
    for g in S:
        N = [_sage_const_0 ]*len(L)
        for x in L:
            i = D[x]
            j = D[action_of_element_as_permutation(g,x)]
            N[i-_sage_const_1 ] = j
        PermGens.append(Permutation(N))
    return PermutationGroup(PermGens)

def is_derangement(x):  # for 3 intersecting
    if len(Permutation(x).fixed_points()) <= _sage_const_2 :
          return True
    else:
        return False

def VA(m):
    t = ''
    for i in range(m):
        if i == m-_sage_const_1 :
            t += 'X{0}'.format(i)
        else:
            t += 'X{0},'.format(i)
    return var(t)

def weights(n,L,M):
    l,m = len(L),len(M)   #L = conj and M char
    print l,m
    V = VA(m)
    var('z')
    CC_size = []
    char_values = []
    Eq = []
    for F in L:
        for x in SymmetricGroup(n).conjugacy_classes_representatives():
            if x.cycle_type() == F:
                CC_size.append([SymmetricGroup(n).conjugacy_class(x).cardinality(),x])
                break
            else:
                pass
    char = [SymmetricGroupRepresentation(M[i]) for i in range(m)]
    print CC_size
    for chi in char:
        phi = chi.to_character()
        t = _sage_const_0 
        for i in range(m):
            t += V[i]*phi(CC_size[i][_sage_const_1 ])*CC_size[i][_sage_const_0 ]
            print chi,V[i],phi(CC_size[i][_sage_const_1 ]),CC_size[i][_sage_const_1 ].cycle_type()
        if phi.values() == [_sage_const_1 ]*len(SymmetricGroup(n).conjugacy_classes_representatives()):
            Eq.append(t == _sage_const_6 *binomial(n,_sage_const_3 ) -_sage_const_1 )  ######## maximum eigenvalue
        else:
            Eq.append(t == -phi.degree())
        Sol = solve(Eq,V)
    print "Weight possible?", len(Sol) != _sage_const_0 
    if len(Sol) == _sage_const_0 :
        return sys.exit()
##################################################################
    G = SymmetricGroup(n)
    derangement_conjugacy_classes_representatives = []
    CC = G.conjugacy_classes_representatives()
    for x in CC:
        if is_derangement(x) == True:
            derangement_conjugacy_classes_representatives.append(x)
    Q = derangement_conjugacy_classes_representatives
    print len(Q)
    W = [_sage_const_0 ]*len(Q)
    for i in range(len(Q)):
        u = Q[i].cycle_type()
        #print u
        for j in range(m):
            if u == Partition(L[j]):
                W[i] = Sol[_sage_const_0 ][j].rhs()
    print "Equation",Eq
    print Sol
    return [Sol[_sage_const_0 ][i].rhs() for i in range(len(Sol[_sage_const_0 ]))],W

def eigenvalues_weights(n,W):
    eigenvalues = []
    G = SymmetricGroup(n)
    derangement_conjugacy_classes_representatives = []
    CC = G.conjugacy_classes_representatives()
    for x in CC:
        if is_derangement(x) == True:
            derangement_conjugacy_classes_representatives.append(x)
    #print derangement_conjugacy_classes_representatives
    Irr = G.irreducible_characters()#
    #Irr = SymmetricGroupRepresentations(n)
    for psi in Irr:
        #phi = psi.to_character()
        s = _sage_const_0 
        L = derangement_conjugacy_classes_representatives
        for i in range(len(L)):
            s += (_sage_const_1 /psi.degree()) * ( W[i]*G.conjugacy_class(L[i]).cardinality()*psi(L[i]) )
        eigenvalues.append(s)
        print (s,psi)
        #if psi.degree() == binomial(n-1,2)-1:
        #    print "ITOOOOOOOOOOOOOOOOOOOOOOOOOOO",s
    return eigenvalues,gap.Minimum(eigenvalues)

n = int(sys.argv[_sage_const_1 ])
W = weights(n,[[n],[n-_sage_const_1 ,_sage_const_1 ],[n-_sage_const_2 ,_sage_const_2 ],[n-_sage_const_3 ,_sage_const_2 ,_sage_const_1 ],[n-_sage_const_3 ,_sage_const_3 ],[n-_sage_const_2 ,_sage_const_1 ,_sage_const_1 ],[n-_sage_const_4 ,_sage_const_3 ,_sage_const_1 ]],[[n],[n-_sage_const_1 ,_sage_const_1 ],[n-_sage_const_2 ,_sage_const_2 ],[n-_sage_const_2 ,_sage_const_1 ,_sage_const_1 ],[n-_sage_const_3 ,_sage_const_3 ],[n-_sage_const_3 ,_sage_const_1 ,_sage_const_1 ,_sage_const_1 ],[n-_sage_const_3 ,_sage_const_2 ,_sage_const_1 ]])
L =  eigenvalues_weights(n,W[_sage_const_1 ])
print L 


def find_derangement_classes_representatives_3_derangements(G):
    P = Partitions(_sage_const_3 )
    CC = G.conjugacy_classes_representatives()
    N = []
    for x in CC:
        if is_derangement(x,P):
            N.append(x)
        else:
            pass
    return N

