

# This file was *autogenerated* from the file ./alternating_graph.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_4 = Integer(4)#!/usr/local/bin/sage


def twist():
    G = graphs.CompleteGraph(_sage_const_4 )
    K = Graph()
    K.add_vertices(['a','b','c','d','e'])
    return G.cartesian_product(K)

G =  twist()
print G.vertices()
for i in ['a','b','c','d','e']:
    for j in ['a','b','c','d','e']:
        if j!= i:
            G.add_edges([((_sage_const_1 ,i),(_sage_const_4 ,j)),((_sage_const_4 ,i),(_sage_const_1 ,j)),((_sage_const_2 ,i),(_sage_const_3 ,j)),((_sage_const_3 ,i),(_sage_const_2 ,j))])

