

# This file was *autogenerated* from the file ./alternating.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0)#!/usr/local/bin/sage

import numpy as np
import sys

def conjugacy_class_scheme(G):
    L = []
    CC = G.conjugacy_classes()
    for C in CC:
        print C
        M = Matrix(G.order(),G.order())
        for i in range(G.order()):
            for j in range(G.order()):
                if G[j]*G[i].inverse() in C:
                    M[i,j] = _sage_const_1 
        L.append(M)
    return L

def is_derangement(x):  # for 2 intersecting
    if len(Permutation(x).fixed_points()) == _sage_const_0 :
          return True
    else:
        return False

def VA(m):
    t = ''
    for i in range(m):
        if i == m-_sage_const_1 :
            t += 'X{0}'.format(i)
        else:
            t += 'X{0},'.format(i)
    return var(t)

def weights(n,L,M):
    l,m = len(L),len(M)   #L = conj and M char
    print l,m
    V = VA(m)
    var('z')
    CC_size = []
    char_values = []
    Eq = []
    for F in L:
        #print AlternatingGroup(n).conjugacy_classes_representatives()
        for x in AlternatingGroup(n).conjugacy_classes_representatives():
            if x.cycle_type() == F:
                CC_size.append([AlternatingGroup(n).conjugacy_class(x).cardinality(),x])
                break
            else:
                pass
    char = [SymmetricGroupRepresentation(M[i]).to_character().restrict(AlternatingGroup(n)) for i in range(m)]
    print CC_size
    for chi in char:
        phi = chi
        t = _sage_const_0 
        for i in range(m):
            t += V[i]*phi(CC_size[i][_sage_const_1 ])*CC_size[i][_sage_const_0 ]
            print V[i],phi(CC_size[i][_sage_const_1 ]),CC_size[i][_sage_const_1 ].cycle_type()
        if phi.values() == [_sage_const_1 ]*len(AlternatingGroup(n).conjugacy_classes_representatives()):
            print "YESSSSSSS"
            Eq.append(t == (n-_sage_const_1 ))  ######## maximum eigenvalue
        else:
            Eq.append(t == -phi.degree())
        Sol = solve(Eq,V)
    print "Weight possible?", len(Sol) != _sage_const_0 
    if len(Sol) == _sage_const_0 :
        return sys.exit()
##################################################################
    G = AlternatingGroup(n)
    derangement_conjugacy_classes_representatives = []
    CC = G.conjugacy_classes_representatives()
    for x in CC:
        if is_derangement(x) == True:
            derangement_conjugacy_classes_representatives.append(x)
    Q = derangement_conjugacy_classes_representatives
    print len(Q)
    W = [_sage_const_0 ]*len(Q)
    for i in range(len(Q)):
        u = Q[i].cycle_type()
        #print u
        for j in range(m):
            if u == Partition(L[j]):
                W[i] = Sol[_sage_const_0 ][j].rhs()
    print "Equation",Eq
    print Sol
    return [Sol[_sage_const_0 ][i].rhs() for i in range(len(Sol[_sage_const_0 ]))],W

def eigenvalues_weights(n,W):
    eigenvalues = []
    G = AlternatingGroup(n)
    derangement_conjugacy_classes_representatives = []
    CC = G.conjugacy_classes_representatives()
    print "length",len(CC)
    for x in CC:
        if is_derangement(x) == True:
            derangement_conjugacy_classes_representatives.append(x)
#    print derangement_conjugacy_classes_representatives
    Irr = G.irreducible_characters()#
    #for f in Irr:
    #    print f.values()
    #print "----------------------------------------------"
    #Irr = SymmetricGroupRepresentations(n)
    for psi in Irr:
        #phi = psi.to_character()
        s = _sage_const_0 
        L = derangement_conjugacy_classes_representatives
        for i in range(len(L)):
            if L[i].cycle_type() == [n] or L[i].cycle_type() == [n-_sage_const_3 ,_sage_const_3 ]: #if conjugacy class splits
                #print "yes"
                #print (1/psi.degree()) * ( 1/2*W[i]*G.conjugacy_class(L[i]).cardinality()*psi(L[i]) )
                s += (_sage_const_1 /psi.degree()) * ( _sage_const_1 /_sage_const_2 *W[i]*G.conjugacy_class(L[i]).cardinality()*psi(L[i]) )
            else:
                s += (_sage_const_1 /psi.degree()) * ( W[i]*G.conjugacy_class(L[i]).cardinality()*psi(L[i]) )
                #print (1/psi.degree()) * ( W[i]*G.conjugacy_class(L[i]).cardinality()*psi(L[i]) )
        eigenvalues.append(s)
        print (s,psi.degree())
        #if psi.degree() == 1:
        #    print "degree 1",s
    return eigenvalues,gap.Minimum(eigenvalues)

def alt_char(n):
    return [_sage_const_1 ]*n

#G = CyclicPermutationGroup(30)
#L = conjugacy_class_scheme(G)
#for X in L:
#    print X,"\n"
#print [G[i] for i in range(G.order())]

#f = open("2-intersecting1.txt","w+")
#for n in filter(is_odd,range(4,16)):
    #W = weighting(n)
    #f.write( "{1} ==> {0} \n".format(eigenvalues_weights(n,W),n))

n = int(sys.argv[_sage_const_1 ])
#W = weighting(n)
#print W

#Alt = alt_char(n)
#print Alt
#W = weights(n,[[n],[n-1,1],[n-2,2],[n-3,2,1]],[[n],[n-1,1],[n-2,2],[n-2,1,1]])
W = weights(n,[[n-_sage_const_2 ,_sage_const_2 ],[n-_sage_const_3 ,_sage_const_3 ]],[[n],[n-_sage_const_1 ,_sage_const_1 ]]) #works for even
#W = weights(n,[[n],[n-4,2,2]],[[n],[n-1,1]]) #works for odd
G = AlternatingGroup(n)
L =  eigenvalues_weights(n,W[_sage_const_1 ])
#U = list(L)
#var('r7')
#r7 = solve(L[0][0] == 0,r7)[0].rhs()
print L[_sage_const_0 ],gap.Minimum(L[_sage_const_0 ])#,L[1], n*(n-1) -1,type(L[0][0])

