
# This file was *autogenerated* from the file ./clique_number.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_5 = Integer(5)#!/usr/local/bin/sage

import functions
import numpy as np

n,k = _sage_const_5 ,_sage_const_2 
X = graphs.KneserGraph(n,k)
X.relabel()
G = X.automorphism_group()
Y = functions.cayleygraph(G)

print Y.clique_number(),binomial()

