

# This file was *autogenerated* from the file ./eigenvalues2-derangements.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0)#!/usr/local/bin/sage

import sys

def  is_derangement(x):
    if len(Permutation(x).fixed_points()) <= _sage_const_1 :
        #if 2 not in x.cycle_type():
          return True
    else:
        return False

def eigenvalues_group(G):
    IRR = G.irreducible_characters()
    derangement_conjugacy_classes_representatives = []
    eigenvalues = []
    CC = G.conjugacy_classes_representatives()
    for x in CC:
        if is_derangement(x) == True:
            derangement_conjugacy_classes_representatives.append(x)
    for phi in IRR:
        s = _sage_const_0 
        for x in derangement_conjugacy_classes_representatives:
            s += (_sage_const_1 /phi.degree()) * ( G.conjugacy_class(x).cardinality()*phi(x) )
        eigenvalues.append(s)
        print s,phi.degree()
    return eigenvalues

def eigenvalues_groupchar(G):
    IRR = SymmetricGroupRepresentations(n)
    derangement_conjugacy_classes_representatives = []
    eigenvalues = []
    CC = G.conjugacy_classes_representatives()
    for x in CC:
        if is_derangement(x) == True:
            derangement_conjugacy_classes_representatives.append(x)
    for psi in IRR:
      phi = psi.to_character()
      s = _sage_const_0 
      for x in derangement_conjugacy_classes_representatives:
          s += (_sage_const_1 /phi.degree()) * ( G.conjugacy_class(x).cardinality()*phi(x) )
      eigenvalues.append((s,psi))
      print s,psi
    return eigenvalues

n = int(sys.argv[_sage_const_1 ])
G = SymmetricGroup(n)
L = eigenvalues_group(G)
print gap.Minimum(eigenvalues_group(G))
#for x in L:
#    print x
print L
print G.stabilizer(_sage_const_1 ).order(),((factorial(n))/(_sage_const_1 - gap.Maximum(L)/gap.Minimum(L))),G.stabilizer(_sage_const_1 ).order()-((factorial(n))/(_sage_const_1 - gap.Maximum(L)/gap.Minimum(L)))

