
# This file was *autogenerated* from the file ./ekr_subgroup.sage
from sage.all_cmdline import *   # import sage library

_sage_const_7 = Integer(7)#!/usr/bin/sage

import group_ekr

G = PermutationGroup(_sage_const_7 )
for H in G.subgroups():
    cayleygraph(H)
    

