
# This file was *autogenerated* from the file ./graph_list.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_10 = Integer(10); _sage_const_9 = Integer(9)#!/usr/local/bin/sage

def graph_list():
    LstJG = []
    for i in range(_sage_const_1 ,_sage_const_10 ):
        for j in range(_sage_const_2 ,_sage_const_9 ):
            LstJG.append(graphs.JohnsonGraph(i,j))

    LstCommonGraphs = [graphs.PapusGraph(),graphs.HeawoodGraph(),graphs.CoxeterGraph(),graphs.TutteCoxeterGraph,graphs.DodecahedralGraph()
    ,graphs.DesarguesGraph(),graphs.BiggsSmithGraph(),graphs.FosterGraph(),graphs.HoffmanSingletonGraph()]

    return LstJG + LstCommonGraphs

