
# This file was *autogenerated* from the file ./graph6.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1)#!/usr/local/bin/sage

f = open("cay10.01.g6","r") #r:= read
L = f.readlines()
Graphs = []
for w in L:
    Graphs.append(Graph(w))
f.close()

def integral_test(L):
    a = True
    for i in L:
        if int(i) != i:
            a = False
            break
    return a


#G = Graphs[0]
for G in Graphs:
    print G.eigenspaces()
    A = G.adjacency_matrix()
    L = G.laplacian_matrix()
    print L
    if integral_test(L) == True:
        print "Eigenvalues of the Laplacian",L.eigenvalues()
        P = L.eigenmatrix_right()[_sage_const_1 ]
        print P.transpose()*P

