

# This file was *autogenerated* from the file ./small_char.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1 = Integer(1)#!/usr/local/bin/sage

import sys

n = int(sys.argv[_sage_const_1 ])



def get_characters(k):
     IRR = SymmetricGroupRepresentations(k)
     chars = []
     for i in range(len(SymmetricGroup(k).conjugacy_classes())):
         g = IRR[i]
         if g.to_character().degree() < _sage_const_2 *binomial(k,_sage_const_2 ):
             chars.append(g)
     return chars

for x in get_characters(n):
    print x

