
# This file was *autogenerated* from the file ./strict-property.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_4 = Integer(4)#!/usr/local/bin/sage

import numpy as np
import sys

def is_derangement(x):  # for 2 intersecting
    if len(Permutation(x).fixed_points()) <= _sage_const_1 :
        if _sage_const_2  not in x.cycle_type():
          return True
    else:
        return False


def VA(m):
    t = ''
    for i in range(m):
        if i == m-_sage_const_1 :
            t += 'X{0}'.format(i)
        else:
            t += 'X{0},'.format(i)
    return var(t)

def weights(n,L,M):
    l,m = len(L),len(M)   #L = conj and M char
    print l,m
    V = VA(m)
    var('z')
    CC_size = []
    char_values = []
    Eq = []
    for F in L:
        for x in SymmetricGroup(n).conjugacy_classes_representatives():
            if x.cycle_type() == F:
                CC_size.append([SymmetricGroup(n).conjugacy_class(x).cardinality(),x])
                break
            else:
                pass
    char = [SymmetricGroupRepresentation(M[i]) for i in range(m)]
    print CC_size
    for chi in char:
        phi = chi.to_character()
        t = _sage_const_0 
        for i in range(m):
            t += V[i]*phi(CC_size[i][_sage_const_1 ])*CC_size[i][_sage_const_0 ]
            print chi,V[i],phi(CC_size[i][_sage_const_1 ]),CC_size[i][_sage_const_1 ].cycle_type()
        if phi.values() == [_sage_const_1 ]*len(SymmetricGroup(n).conjugacy_classes_representatives()): ###nothing happens here, I replaced [0]* with [1]*
            Eq.append(t == (n-_sage_const_1 )*n/_sage_const_2  -_sage_const_1 )  ######## maximum eigenvalue
        else:
            Eq.append(t == -phi.degree())
        Sol = solve(Eq,V)
    print "Weight possible?", len(Sol) != _sage_const_0 
    if len(Sol) == _sage_const_0 :
        return sys.exit()
##################################################################
    G = SymmetricGroup(n)
    derangement_conjugacy_classes_representatives = []
    CC = G.conjugacy_classes_representatives()
    for x in CC:
        if is_derangement(x) == True:
            derangement_conjugacy_classes_representatives.append(x)
    Q = derangement_conjugacy_classes_representatives
    print len(Q)
    W = [_sage_const_0 ]*len(Q)
    for i in range(len(Q)):
        u = Q[i].cycle_type()
        print u
        for j in range(m):
            #print "#",[u, Partition(L[j])]
            if u == Partition(L[j]):
                W[i] = Sol[_sage_const_0 ][j].rhs()
    print "Equation",Eq
    print "solution",Sol
    print "Wito",W
    return [Sol[_sage_const_0 ][i].rhs() for i in range(len(Sol[_sage_const_0 ]))],W

def eigenvalues_weights(n,W):
    eigenvalues = []
    G = SymmetricGroup(n)
    derangement_conjugacy_classes_representatives = []
    CC = G.conjugacy_classes_representatives()
    for x in CC:
        if is_derangement(x) == True:
            derangement_conjugacy_classes_representatives.append(x)
    #print derangement_conjugacy_classes_representatives
    Irr = G.irreducible_characters()#
    #Irr = SymmetricGroupRepresentations(n)
    for psi in Irr:
        #phi = psi.to_character()
        s = _sage_const_0 
        L = derangement_conjugacy_classes_representatives
        for i in range(len(L)):
            s += (_sage_const_1 /psi.degree()) * ( W[i]*G.conjugacy_class(L[i]).cardinality()*psi(L[i]) )
        eigenvalues.append(s)
        a,b = _sage_const_0 ,_sage_const_0 
        a = SymmetricGroupRepresentation([_sage_const_2 ]+(n-_sage_const_2 )*[_sage_const_1 ]).to_character().values()
        b = SymmetricGroupRepresentation([_sage_const_2 ,_sage_const_2 ]+(n-_sage_const_4 )*[_sage_const_1 ]).to_character().values()
        c = SymmetricGroupRepresentation([n-_sage_const_1 ,_sage_const_1 ]).to_character().values()
        d = SymmetricGroupRepresentation([n-_sage_const_2 ,_sage_const_2 ]).to_character().values()
        if psi.values() == a:
            print "[2,1^{n-2}]",eigenvalues[-_sage_const_1 ]
        if psi.values() == b:
            print "[2^2,1^{n-4}]", eigenvalues[-_sage_const_1 ]
        if psi.values() == c:
            print "[n-1,1]", eigenvalues[-_sage_const_1 ]
        if psi.values() == d:
            print "[n-2,2]",eigenvalues[-_sage_const_1 ]
    return eigenvalues,gap.Minimum(eigenvalues)



n = int(sys.argv[_sage_const_1 ])


W = weights(n,[[n-_sage_const_3 ,_sage_const_3 ],[n-_sage_const_1 ,_sage_const_1 ]],[[n-_sage_const_1 ,_sage_const_1 ],[n-_sage_const_2 ,_sage_const_2 ]])
print "W",W
G = SymmetricGroup(n)
k = len(G.conjugacy_classes())

L =  eigenvalues_weights(n,W[_sage_const_1 ])
#U = list(L)
#var('r7')
#r7 = solve(L[0][0] == 0,r7)[0].rhs()
print L[_sage_const_0 ],gap.Minimum(L[_sage_const_0 ]),L[_sage_const_1 ]
print n*(n-_sage_const_1 ) -_sage_const_1 ,type(L[_sage_const_0 ][_sage_const_0 ])

