
# This file was *autogenerated* from the file ./transitive.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_4 = Integer(4); _sage_const_500 = Integer(500); _sage_const_30 = Integer(30)#!/usr/local/bin/sage

def get_derangements(G):
    Drep = []
    D = []
    CC = G.conjugacy_classes_representatives()
    for x in CC:
        if is_derangement(G,x) == True:
            Drep.append(x)
        else:
            pass
    for x in Drep:
          D += list(G.conjugacy_class(x))
    return D
    #return filter(is_derangement,G)
def is_derangement(G,x):  # needs G to be defined beforehand
    for i in G.domain():
        if x(i) == i:
            return False
        else:
            pass
    return True

def eigenvalues_group(G):
    IRR = G.irreducible_characters()
    derangement_conjugacy_classes_representatives = []
    eigenvalues = []
    CC = G.conjugacy_classes_representatives()
    for x in CC:
        if is_derangement(G,x) == True:
            derangement_conjugacy_classes_representatives.append(x)
    for phi in IRR:
        s = _sage_const_0 
        for x in derangement_conjugacy_classes_representatives:
            s += (_sage_const_1 /phi.degree()) * ( G.conjugacy_class(x).cardinality()*phi(x) )
        eigenvalues.append(s)
    return list(eigenvalues),gap.Minimum(eigenvalues),gap.Maximum(eigenvalues)

def eigenvalues_group_and_multi(G):
    IRR = G.irreducible_characters()
    derangement_conjugacy_classes_representatives = []
    eigenvalues, multiplicity = [], []
    CC = G.conjugacy_classes_representatives()
    for x in CC:
        if is_derangement(G,x) == True:
            derangement_conjugacy_classes_representatives.append(x)
    for phi in IRR:
        s = _sage_const_0 
        for x in derangement_conjugacy_classes_representatives:
            s += (_sage_const_1 /phi.degree()) * ( G.conjugacy_class(x).cardinality()*phi(x) )
        eigenvalues.append(s)
        multiplicity.append(phi(G.identity())**_sage_const_2 )
    return eigenvalues,multiplicity

def eigenvalues_group_and_characters(G):
    IRR = G.irreducible_characters()
    derangement_conjugacy_classes_representatives = []
    eigenvalues_characters = []
    CC = G.conjugacy_classes_representatives()
    for x in CC:
        if is_derangement(G,x) == True:
            derangement_conjugacy_classes_representatives.append(x)
    for phi in IRR:
        s = _sage_const_0 
        for x in derangement_conjugacy_classes_representatives:
            s += (_sage_const_1 /phi.degree()) * ( G.conjugacy_class(x).cardinality()*phi(x) )
        eigenvalues_characters.append([s,phi.values()])
    return list(eigenvalues_characters)

def derangement_graph(G):
    D = get_derangements(G)
    X = G.cayley_graph(generators = D)
    X = Graph(X)
    return X

def test_groups(L,K):
    j = _sage_const_0 
    f = open("imprimitiveeeeEKR4.txt","w+")
    for i in range(len(L)):
        j += _sage_const_1  #not needed anymore if the list is a sage list not a GAP one.
        G = L[i]
        #print gap.Print(K[j])
        Y = derangement_graph(G)
        independent_number = Y.independent_set(value_only = True)
        #clique_number = Y.clique_number()
        evalue_multiplicity = eigenvalues_group_and_multi(G)
        eigenvalues = list(evalue_multiplicity[_sage_const_0 ])
        multiplicity = list(evalue_multiplicity[_sage_const_1 ])
        evalue_min_max = eigenvalues_group(G)
        print "----------------------------------------------------------"
        print "\t No",int(i+_sage_const_1 )
        print "\n group =",gap.StructureDescription(K[i])
        print " Size = ",G.order()
        print " Domain = ",G.domain()
        #print " Generators = ",G.gens()
        print " Independence number = ",independent_number, "\n stabilizer = ",G.stabilizer(_sage_const_1 ).order()
        print " EKR",G.stabilizer(_sage_const_1 ).order() == independent_number
        print " eigenvalues",eigenvalues
        print " multiplicity", multiplicity
        print " Blocks",G.blocks_all()
        print " Join", evalue_min_max[_sage_const_2 ]-evalue_min_max[_sage_const_1 ] == G.order()
        print " ratio-bound", (G.order())/(_sage_const_1 -(evalue_min_max[_sage_const_2 ]/evalue_min_max[_sage_const_1 ]))
        f.write("----------------------------------------------------------------------------- \n \t No {0}\n group = {1}\n Size = {2}\n Domain = {6} \n EKR {3}\n eigenvalues = {4}\n multiplicity = {7} \n Blocks = {5}\n \n----------------------------------------------------------------------------- \n".format(int(i+_sage_const_1 ),gap.StructureDescription(K[i]),G.order(),G.stabilizer(_sage_const_1 ).order() == independent_number,eigenvalues,G.blocks_all(),G.domain(),multiplicity))
    print "----------------------------------------------------------"
    f.close()


def divide_lists(L,k):
    S = []
    s = len(L)%k
    q = (len(L)-s)/k
    for i in range(q):
        S.append([L[j] for j in range(i*k,i*k+k)])
    if s != _sage_const_0  :
        S.append([L[i] for i in range(q*k,q*k+s)])
    return S

def fixed_pts(g):
    return len(Permutation(g).fixed_points())

def fix_char(G):
    derangement_conjugacy_classes_representatives = []
    CC = G.conjugacy_classes_representatives()
    for x in CC:
        if is_derangement(G,x) == True:
            derangement_conjugacy_classes_representatives.append(x)
    s = _sage_const_0 
    for x in derangement_conjugacy_classes_representatives:
        s += ( G.conjugacy_class(x).cardinality()*(fixed_pts(x)-_sage_const_1 ) )
    return s

#print divide_lists(range(500),9)
L = gap.AllTransitiveGroups(gap.NrMovedPoints,(ellipsis_range(_sage_const_1 ,Ellipsis,_sage_const_30 )),gap.Size,[_sage_const_3 **i for i in range(_sage_const_1 ,_sage_const_4 )],gap.IsPrimitive,gap.false)
L = list(L)
print "List of size ",len(L)
Q = divide_lists(L,_sage_const_500 )
#print "a"
#print LL
#print Q
for X in Q:
    LL = [PermutationGroup(gap.Elements(G)) for G in X]
    test_groups(LL,X)
#print L[0]

